site_name: Flux Helm Operator
# site_description:
site_author: The Helm Operator contributors
site_url: https://docs.fluxcd.io/projects/helm-operator/

# Repository
repo_name: fluxcd/helm-operator
repo_url: https://github.com/fluxcd/helm-operator
edit_uri: ""

extra:
  version: 1.0.1
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/fluxcd/helm-operator

theme:
  name: material
  logo: _files/flux-icon@2x.png
  favicon: _files/flux-icon@2x.png
  language: en
  palette:
    primary: blue
    accent: indigo

docs_dir: docs

extra_css:
  - _static/custom.css

plugins:
  - search
  - markdownextradata: {}
  - redirects:
      redirect_maps:
        'guides/upgrading-to-ga.md': 'how-to/upgrade-to-ga.md'
        'guides/upgrading-to-beta.md': 'how-to/upgrade-to-beta.md'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.tabbed

nav:
  - Overview: index.md
  - Get started:
    - Quickstart: get-started/quickstart.md
    - Using Helm: get-started/using-helm.md
    - Using Kustomize: get-started/using-kustomize.md
    - Using YAMLs: get-started/using-yamls.md
  - References:
    - Operator reference: references/operator.md
    - HelmRelease Custom Resource: references/helmrelease-custom-resource.md
    - Helm chart: references/chart.md
    - Monitoring: references/monitoring.md
  - HelmRelease guide:
    - Introduction: helmrelease-guide/introduction.md
    - Chart sources: helmrelease-guide/chart-sources.md
    - Values: helmrelease-guide/values.md
    - Release configuration: helmrelease-guide/release-configuration.md
    - Reconciliation and upgrades: helmrelease-guide/reconciliation-and-upgrades.md
    - Rollbacks: helmrelease-guide/rollbacks.md
    - Automation: helmrelease-guide/automation.md
    - Debugging: helmrelease-guide/debugging.md
  - How-to:
    - Upgrade to GA: how-to/upgrade-to-ga.md
    - Upgrade to beta: how-to/upgrade-to-beta.md
  - Troubleshooting:
    - FAQ: faq.md
    - Troubleshooting: troubleshooting.md
  - Contributing:
    - Introduction: contributing/introduction.md
    - Building: contributing/building.md
    - Get started developing: contributing/get-started-developing.md
